// Wraps the backend's admin-only AccountingPeriodController
// (/api/admin/accounting-periods/**, requires ROLE_ADMIN). Periods are only
// ever generated by FiscalYearServiceImpl (one per calendar month) — there's
// no create endpoint here, only list/close/reopen.

import type { ApiEnvelope, PageEnvelope } from '#shared/types'

export type AccountingPeriodStatus = 'OPEN' | 'CLOSED'

export interface AccountingPeriod {
  id: number
  fiscalYearId: number
  fiscalYearName: string | null
  companyId: number
  periodNumber: number
  name: string
  startDate: string
  endDate: string
  status: AccountingPeriodStatus
}

export interface AccountingPeriodFilter {
  companyId?: number
  fiscalYearId?: number
  status?: AccountingPeriodStatus
  sortBy?: string
  sortOrder?: 'asc' | 'desc'
  page?: number
  size?: number
}

export function useAccountingPeriods() {
  const api = useApi()

  function list(filter: AccountingPeriodFilter = {}) {
    return api<PageEnvelope<AccountingPeriod>>('/api/admin/accounting-periods', { query: filter })
  }

  async function get(id: number) {
    const res = await api<ApiEnvelope<AccountingPeriod>>(`/api/admin/accounting-periods/${id}`)
    return res.data
  }

  async function close(id: number) {
    const res = await api<ApiEnvelope<AccountingPeriod>>(`/api/admin/accounting-periods/${id}/close`, { method: 'POST' })
    return res.data
  }

  async function reopen(id: number) {
    const res = await api<ApiEnvelope<AccountingPeriod>>(`/api/admin/accounting-periods/${id}/reopen`, { method: 'POST' })
    return res.data
  }

  return { list, get, close, reopen }
}
